name: Build Flutter APK

on:
  workflow_dispatch: {}
  push:
    paths:
      - "lib/**"
      - "pubspec.yaml"
      - ".github/workflows/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Setup Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter version
        run: flutter --version

      - name: Create Android platform (if missing)
        run: flutter create . --platforms=android

      - name: Get packages
        run: flutter pub get

      - name: Build debug APK
        run: flutter build apk --debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: bbk-ocr-starter-debug
          path: build/app/outputs/flutter-apk/app-debug.apk
